// examples/vite-react-basic/src/App.tsx
import { useEffect } from "react";
import { getSerwist } from "virtual:serwist";
import "./App.css";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";

function App() {
  useEffect(() => {
    if ("serviceWorker" in navigator) {
      const serwist = getSerwist();
      serwist?.addEventListener("installed", () => {
        console.log("Serwist installed!");
      });
      void serwist?.register();
    }
  });

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React + Serwist</h1>
    </>
  );
}

export default App;

// examples/vite-solid-basic/src/App.tsx
import { useSerwist } from "virtual:serwist/solid";
import { type Component, createEffect } from "solid-js";
import styles from "./App.module.css";
import logo from "./logo.svg";

const App: Component = () => {
  const serwist = useSerwist();
  createEffect(() => {
    const swst = serwist();
    if (!swst) return;
    swst.addEventListener("installed", () => {
      console.log("Serwist installed!");
    });
    void swst.register();
  });
  return (
    <div class={styles.App}>
      <header class={styles.header}>
        <img src={logo} class={styles.logo} alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a class={styles.link} href="https://github.com/solidjs/solid" target="_blank" rel="noopener noreferrer">
          Learn Solid
        </a>
      </header>
    </div>
  );
};

export default App;
